### ISSUE TITLE
in re license

### ISSUE THREAD

**Issue by danrubins** [digitallawyer/openlegaldictionary#1]
To whom it may concern:
Being of the esteemed legal profession, Y U NO [LICENSE](https://openlegaldictionary.com/definitions/bld-license.html)?

The submitting party of this issue (hereafter "dhrubins") doth herein make such humble request whereby the publishing party of some multiple repositories (hereafter "digitallawyer") do effect the rightful submission of a license to this repository. This hereby concludes the submission of this issue, _in toto_. 

![79a](https://user-images.githubusercontent.com/5916119/43805045-21db2204-9a53-11e8-8c40-3404be120677.gif)

**Comment by digitallawyer** [comment]
@dhrubins for the avoidance of doubt, are you noting that this repo should have a license (would be MIT) or that a certain license that needs to be included was not?

**Comment by digitallawyer** [comment]
(I'll fix either way.)

**Comment by danrubins** [comment]
:) 
I just noticed it didn't have a license and I'd love to contribute to & use it

**Comment by digitallawyer** [comment]
Thank you for flagging! Clearly my legal mind was not as active as it should be this weekend. 

Here is the [commit](https://github.com/digitallawyer/openlegaldictionary/commit/9f14a00b4f8f4ff1c4d7ff968f8b282e61ffe258) resolving this issue.

**Comment by danrubins** [comment]
👍
